{% set version = "2.5" %}

package:
  name: gsl
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gsl/gsl-{{ version }}.tar.gz
  sha256: 0460ad7c2542caaddc6729762952d345374784100223995eb14d614861f2258d
  patches:
    # diff from source distribution to https://github.com/ampl/gsl/tree/v2.4.0
    - patch_cmake_for_windows.diff  # [win]
    # avoid "make check" error: https://savannah.gnu.org/bugs/?52927
    - bessel_test.diff

build:
  number: 0
  features:
  run_exports:
    # tends to break at minor revs
    #    https://abi-laboratory.pro/index.php?view=timeline&l=gsl
    - {{ pin_subpackage("gsl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - cmake  # [win]
  host:
    - libblas
    - libcblas
  run:

test:
  commands:
    - gsl-config --prefix  # [not win]
    - if not exist %LIBRARY_LIB%\\gsl.lib       exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\gslcblas.lib  exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\gsl.dll       exit 1   # [win]
    - ls -al $PREFIX/lib/libgslcblas.so.0      # [linux]
    - ls -al $PREFIX/lib/libgslcblas.so        # [linux]
    - ls -al $PREFIX/lib/libgslcblas.0.dylib   # [osx]
    - ls -al $PREFIX/lib/libgslcblas.dylib     # [osx]

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0
  license_file: COPYING
  summary: 'GNU Scientific Library'

extra:
  recipe-maintainers:
    - kwilcox
    - mingwandroid
    - ocefpaf
